manifest:
    defaults:
        revision: main
    remotes:
        - name: caksoylar
          url-base: https://github.com/caksoylar
        - name: nickconway
          url-base: https://github.com/nickconway
    projects:
        - name: zmk-rgbled-widget
          remote: caksoylar
          path: extra-modules/zmk-rgbled-widget
        - name: zmk-component-sharp-display
          remote: nickconway
          path: extra-modules/sharp-display
    self:
        path: config
